# Generated by Django 4.1.1 on 2022-09-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_skill_remove_myuser_bio_myuser_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('company_display_name', models.CharField(max_length=256)),
                ('category_label', models.CharField(max_length=256)),
                ('location_display_name', models.CharField(max_length=256)),
                ('job_id', models.IntegerField()),
                ('job_posting_url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='saved_jobs',
            field=models.ManyToManyField(to='main_app.job'),
        ),
    ]
