# Generated by Django 4.1.1 on 2022-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_job_myuser_saved_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category_label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_display_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='location_display_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.TextField(),
        ),
    ]
