# Generated by Django 4.1.1 on 2022-09-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_job_category_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.BigIntegerField(),
        ),
    ]
